INSERT INTO CURRENCY_EXCHANGE (CODE_ID, CODE_FROM, CODE_TO, CONVERSION_RATE, SERVICE_NAME) VALUES (1001, 'USD', 'INR', 70, null);
INSERT INTO CURRENCY_EXCHANGE (CODE_ID, CODE_FROM, CODE_TO, CONVERSION_RATE, SERVICE_NAME) VALUES (1002, 'EUR', 'INR', 80, null);
INSERT INTO CURRENCY_EXCHANGE (CODE_ID, CODE_FROM, CODE_TO, CONVERSION_RATE, SERVICE_NAME) VALUES (1003, 'CAD', 'INR', 50, null);
select * from Currency_Exchange;